### PR TITLE
fixing slugs and routing paths

### LINKED ISSUE #38: Slugs for each Controller (except Proficiency)
Following in the footsteps of the Proficiency Slug bug #31 , adding slugs to each controller seems wise.

### PR DESCRIPTION
**Pull request by aizon2456**
Fixes #38 and a couple of routing problems

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -18,7 +18,10 @@ def permission_check
 
   # Check if logged in, and if not, then redirect
   def check_if_logged_on
-    if request.path != "/login"
+    #get the current path and verify that the users are logged in, or trying to login/signup
+    controller = params[:controller]
+    action = params[:action]
+    if request.path != "/login" && request.path != "/signup" && !(controller == "users" && action == "create")
```
Comment (Rosengren) [inline app/controllers/application_controller.rb:24]: Is it possible to have a whitelist for links that can be accessed without being logged in? Maybe an array or something? In the future, we might add other links like Landing page, about page, contact page, etc. It's not that important but maybe something to think about

**Comment by Rosengren** [comment]
Looks good! I'll let you merge it in case you want to make any last minute changes :)

seal of approval

File: app/controllers/application_controller.rb (hunk 1 above)
Comment (aizon2456) [inline app/controllers/application_controller.rb:24]: Yep, I'll open a new issue and fix that!
